app/models.py
from . import db
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash
from . import login_manager
from flask_login import UserMixin
from datetime import datetime


class Student(UserMixin, db.Model):
    '''
    student class model 
    '''
    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(255), index=True)
    pass_secure = db.Column(db.String(255))
    email = db.Column(db.String(255), unique=True, index=True)
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())


    # def __repr__(self):
    #     return f'User {self.username}'

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.pass_secure = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.pass_secure, password)

    # def __repr__(self):
    #     return f'User {self.username}'

    @login_manager.user_loader
    def load_user(user_id):
        return Student.query.get(int(user_id))


class Courses(db.Model):
    '''
    Courses model for student
    '''
    __tablename__ = 'courses'

    id = db.Column(db.Integer, primary_key=True)
    course_id = db.Column(db.Integer)
    course = db.Column(db.String(255), index=True)
    content = db.Column(db.String(), index=True)
    # from foreign key
    # pitch_id = db.relationship('Pitch', backref='category', lazy="dynamic")


class Exercise(db.Model):
    '''
    Exercise
    '''
    __tablename__ = 'exercise'

    id = db.Column(db.Integer, primary_key=True)
    pitch_id = db.Column(db.Integer)
    exercise = db.Column(db.String(255))
    Question = db.Column(db.String(255))

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField
from wtforms.validators import Required


class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you.',validators = [Required()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
# from flask_simplemde import SimpleMDE

login_manager = LoginManager()
'''
login_manager.session_protection attribute provides different security levels like setting it to strong
'''
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

bootstrap = Bootstrap()
db = SQLAlchemy()
photos = UploadSet('photos',IMAGES)

def create_app(config_name):

    app = Flask(__name__)

    # Creating the app configurations
    app.config.from_object(config_options[config_name])
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/auth')

    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)

     # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    # configure UploadSet
    configure_uploads(app,photos)

    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views, errors

app/main/views.py
from flask import render_template, request, redirect, url_for, abort

from flask_login import login_required, current_user
from ..models import Student, Courses, Exercise
from .forms import UpdateProfile

# importing main from main blueprint
from . import main
# importing database
from .. import db,photos

@main.route('/')
def index():

    '''
    View of root page function that returns the index page and its data
    '''
    
    return render_template('index.html')

@main.route('/html')
def html():
    '''
    View of page that has html course
    '''

    return render_template('my_html.html')

@main.route('/css')
def css():
    '''
    View of page that has css course
    '''
    return render_template('my_css.html')

@main.route('/science')
def science():
    '''
    View of page that has computer science course
    '''
    return render_template('science.html')

@main.route('/user/<username>')
def profile(username):

    '''
    View of page function that returns the the user's profile
    '''

    user = Student.query.filter_by(username = username).first()

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user = user)

@main.route('/user/<username>/update',methods = ['GET','POST'])
@login_required
def update_profile(username):
    user = Student.query.filter_by(username = username).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',username=user.username))

    return render_template('profile/update.html',form =form)

@main.route('/user/<username>/update/pic',methods= ['POST'])
@login_required
def update_pic(username):
    user = Student.query.filter_by(username = username).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile',username=username))

app/templates/base.html
{% extends 'bootstrap/base.html'%}

{% block styles%}
{{ super() }}
<link rel="stylesheet"
      href="{{url_for('static',filename='css/index.css')}}">

{% endblock %}

<!-- Navbar block  -->
{% block navbar %}
{% include 'navbar.html' %}
{% endblock %}

app/templates/exercise.html
<h1>quiz</h1>
<form action='/quiz' method='POST'>
    <ol>
        {% for i in q %}
            <li>What does the tag <u>{{i}}</u> do?</li>
            {% for j in o[i] %}
                <input type='radio' value='{{j}}' name='{{i}}' />{{j}}
            {% endfor %}
        {% endfor %}
    </ol>
    <input type="submit" value="submit" />
</form>

app/templates/index.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <p>welcome to the lms</p>
        <p><a href="{{url_for('main.html')}}">html</a></p>
        <p><a href="{{url_for('main.css')}}">css</a></p>
        <p><a href="{{url_for('main.science')}}">comp science</a></p>
    </div>
{% endblock %}

app/templates/my_css.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-10">
                <h2>Welcome to the CSS Course</h2>
            </div>
        </div>
    </div>
{% endblock  %}

app/templates/my_html.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-10">
                <h2>Welcome to the HTML Course</h2>
            </div>
        </div>
    </div>
{% endblock  %}

app/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">

	<div class="collapse navbar-collapse" id="navbarColor01">
	<!-- <ul class="navbar-nav mr-auto"> -->
		<ul class="nav navbar-nav navbar-right">
		{% if current_user.is_authenticated %}
			<li><button type="button" class="btn btn-warning btn-lg"><a href="{{url_for('.index')}}">Home</a></button></li>
			<li><button type="button" class="btn btn-danger btn-lg"><a href="{{url_for('auth.logout')}}">Sign out</a></li>

			<li><button type="button" class="btn btn-warning btn-lg"><a href="{{url_for('main.profile',username=current_user.username)}}">{{current_user.username}}</a></button></li>
		{% else %}
			<li><button type="button" class="btn btn-warning btn-lg"><a href="{{url_for('auth.login')}}">Home</a></button></li>
			<li><button type="button" class="btn btn-warning btn-lg"><a href="{{url_for('auth.login')}}">Sign in</a></button></li>
		{% endif %}
		</ul>
		
	</div>
</nav>

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
<div class="container">
<div class="row">
<!-- displaying  Username-->
  <div class="col-md-4">
    <h3> {{user.username| capitalize}} </h3>

    <!--Displaying user bio-->
    {% if user.bio %}
      <p> {{user.bio}}</p>
    {% else %}
      <p> {{user.username| capitalize}} has no bio </p>
    {% endif %}
  </div>

  <!--Display profile photo-->
  <div class="col-md-5">

    {% if user.profile_pic_path %}
    <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">
    {% else %}
    <p>No profile picture</p>
    {% endif %}
    {% if user == current_user %}
    <form  action="{{url_for('main.update_pic',username=user.username)}}" method="post" enctype = "multipart/form-data">
      <input type="file"  name="photo" class="form-control" required>
      <input type="submit">
    </form>
    {% endif %}
  </div>
  <div class="col-md-3">
    {% if user == current_user %}
    <a href="{{url_for('main.update_profile',username=user.username)}}">Edit profile</a>
    {% endif %}
    
  </div>
</div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>
{% endblock %}

app/templates/science.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-10">
                <h2>Welcome to the Computer Science Course</h2>
            </div>
        </div>
    </div>
{% endblock  %}